# Generated by Django 4.1.7 on 2023-06-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_uploads_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploads',
            new_name='Upload',
        ),
    ]
